import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Privacy Policy — LicenseSizer", description: "How LicenseSizer processes dealership settings and customer workflow activity without storing license images or PDFs." };

export default function PrivacyPage() {
  return <LegalShell eyebrow="Trust center" title="Privacy Policy" intro="LicenseSizer is designed to keep driver's-license images and generated PDFs out of our systems while giving dealerships the configuration and activity information needed to operate the service.">
    <section><h2>What this policy covers</h2><p>This policy describes information processed by the LicenseSizer website, dealership console, branded customer pages, and related support and billing services. A dealership may have its own privacy notice governing why it requests a license and how it handles a file after the customer sends it.</p></section>
    <section><h2>License images and PDFs</h2><p>License images are opened and processed in volatile browser memory on the customer’s device. The browser creates the corrected images and PDF locally. LicenseSizer does not provide an image or PDF upload endpoint and does not receive or store those files.</p><p>If a customer downloads or shares a PDF, the browser, operating system, selected application, recipient, and dealership control the file after that point. LicenseSizer cannot see which share target or recipient the customer chooses and cannot confirm delivery.</p></section>
    <section><h2>Information we process</h2><ul><li>Dealer account and organization information supplied through our identity provider.</li><li>Dealership branding, public contact details, handoff destinations, document policies, and team roles.</li><li>Subscription status, Stripe customer and subscription identifiers, and billing-period information. LicenseSizer does not receive complete payment-card numbers.</li><li>Minimal workflow events such as session started, front or back captured, PDF created, share sheet opened, downloaded, email draft opened, text draft opened, and session cleared.</li><li>Technical server records needed for security, reliability, fraud prevention, and troubleshooting, which may include request time, network address, browser information, and error details.</li><li>Communications sent to support, privacy, or security contacts.</li></ul></section>
    <section><h2>Information excluded from workflow events</h2><p>Workflow events do not include customer names, filenames, license numbers, document contents, image bytes, PDF bytes, message bodies, crop geometry, or the recipient selected in another application.</p></section>
    <section><h2>How we use information</h2><ul><li>Provide and secure the service.</li><li>Authenticate dealership users and enforce organization roles.</li><li>Apply dealership capture and handoff settings.</li><li>Show aggregate preparation and handoff-option activity to authorized dealership administrators.</li><li>Operate subscriptions, prevent abuse, troubleshoot incidents, and improve reliability.</li><li>Comply with applicable law and enforce our terms.</li></ul></section>
    <section><h2>Service providers</h2><p>We use service providers for hosting, authentication, database infrastructure, and subscription billing. Their current roles are listed on our <a href="/subprocessors">Subprocessors page</a>. We do not sell personal information or use license workflow information for behavioral advertising.</p></section>
    <section><h2>Retention and deletion</h2><p>License images and PDFs are not retained by LicenseSizer. Dealership configuration, account, subscription, security, and workflow records are retained while needed to provide the service, meet contractual or legal obligations, resolve disputes, prevent fraud, and maintain appropriate business records. A dealership administrator may request account and configuration deletion through Support, subject to records we must retain.</p></section>
    <section><h2>Security and choices</h2><p>Our safeguards and residual risks are summarized on the <a href="/security">Security page</a>. Customers may stop before creating or sharing a PDF, choose a different recipient, download the file, or clear the in-browser session. Dealership administrators can update public and handoff settings from the console.</p></section>
    <section><h2>Children and changes</h2><p>LicenseSizer is a business service and is not directed to children. We may update this policy as the service or legal requirements change. The effective date above identifies the current version.</p></section>
    <section><h2>Contact</h2><p>Privacy questions and requests can be sent to <a href="mailto:privacy@licensesizer.com">privacy@licensesizer.com</a>. Please do not email license images, PDFs, or other identity documents.</p></section>
  </LegalShell>;
}
