import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Terms of Service — LicenseResizer", description: "Terms governing dealership and customer use of LicenseResizer." };

export default function TermsPage() {
  return <LegalShell eyebrow="Trust center" title="Terms of Service" intro="These terms define the responsibilities of LicenseResizer, subscribing dealerships, dealership users, and customers who use a dealership link.">
    <section><h2>Service</h2><p>LicenseResizer provides browser-based tools that help a user capture, crop, resize, create, download, and share a driver’s-license PDF. It also provides dealership branding, configuration, team access, subscriptions, and minimal activity reporting.</p></section>
    <section><h2>No verification or confirmed delivery</h2><p>LicenseResizer does not authenticate a license, verify identity, check expiration, perform a background or credit check, determine legal sufficiency, choose a recipient, send a file on the customer’s behalf, or confirm receipt. Activity reporting shows actions opened in the service, not proof of delivery.</p></section>
    <section><h2>Dealership responsibilities</h2><p>Each dealership is responsible for determining its lawful purpose and authority to request identity documents; providing required notices and obtaining any required consent; configuring an accurate destination; limiting team access; safeguarding documents received outside LicenseResizer; defining retention and deletion practices; and complying with applicable privacy, consumer-protection, financial-services, employment, and records laws.</p></section>
    <section><h2>User responsibilities</h2><p>Users must review the crop and PDF, verify the displayed dealership and destination, choose the intended application and recipient, and confirm that any attachment was included before sending. Users must not submit another person’s document without authorization.</p></section>
    <section><h2>Acceptable use</h2><p>You may not use LicenseResizer to impersonate another person; collect documents deceptively or without authority; facilitate fraud, harassment, spam, discrimination, or unlawful surveillance; probe or disrupt the service; bypass access controls; introduce malicious code; or infringe another person’s rights.</p></section>
    <section><h2>Accounts and administration</h2><p>Dealership users must provide accurate account information, protect their credentials, use appropriate organization roles, and promptly remove access that is no longer required. Organization administrators are responsible for actions performed through their organization.</p></section>
    <section><h2>Trials, fees, and cancellation</h2><p>A stated free trial begins without payment details when offered. If no payment method is added before the trial ends, the trial subscription cancels. Paid fees, billing periods, taxes, renewals, and cancellation options are presented during checkout or in the billing portal. Access to public dealership links may end when a trial or subscription is no longer active.</p></section>
    <section><h2>Availability and changes</h2><p>We may modify, suspend, or discontinue features to maintain security, comply with law, or improve the service. We do not guarantee uninterrupted availability or that every browser, device, email application, or messaging application will support file sharing.</p></section>
    <section><h2>Disclaimers and responsibility</h2><p>The service is provided on an “as available” basis to the extent permitted by law. Dealerships and users remain responsible for reviewing output and for their handling of documents outside LicenseResizer. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded.</p></section>
    <section><h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:legal@licenseresizer.com">legal@licenseresizer.com</a>. Please do not send identity documents by email.</p></section>
  </LegalShell>;
}
