import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Security — LicenseSizer", description: "LicenseSizer security architecture, data boundaries, safeguards, and responsible disclosure." };

export default function SecurityPage() {
  return <LegalShell eyebrow="Trust center" title="Security at LicenseSizer" intro="Our primary security control is data minimization: driver's-license images and generated PDFs are processed locally and are not uploaded to LicenseSizer.">
    <section><h2>Data boundary</h2><p>The browser decodes, analyzes, corrects, and composes the document on the user’s device. Source images and generated PDFs remain in volatile browser memory unless the user downloads or shares them. No LicenseSizer image or PDF ingestion endpoint exists.</p></section>
    <section><h2>Application safeguards</h2><ul><li>HTTPS with strict transport security and restrictive browser security headers.</li><li>Organization authentication and role enforcement through Clerk.</li><li>Server-side organization and administrator authorization on dealer APIs.</li><li>Signed Stripe webhook verification.</li><li>Allowlisted, size-limited workflow events that exclude document content.</li><li>Same-origin image-processing and PDF dependencies.</li><li>Source metadata removal through browser decoding and canvas re-encoding.</li><li>Encoded-file and decoded-pixel limits for untrusted images.</li><li>Camera-track shutdown and object-URL cleanup when sessions are cleared or replaced.</li><li>A service-worker policy that excludes images, media, Blob URLs, and PDFs from application caching.</li></ul></section>
    <section><h2>What activity reporting means</h2><p>Authorized dealer administrators can see preparation and handoff-option events. A “share sheet opened,” “email draft opened,” “text draft opened,” or “downloaded” event is not proof that the customer sent a file or that the dealership received it.</p></section>
    <section><h2>Residual risks</h2><p>Risk remains in the customer’s browser and operating system, downloaded files, selected share applications and recipients, dealership systems, compromised devices, third-party providers, public dealer-link discovery, and inaccurate or poor-quality source images. Printer scaling can also change physical output.</p></section>
    <section><h2>Dealership security responsibilities</h2><p>Dealerships remain responsible for their information-security program, access controls, workforce practices, vendor oversight, secure receipt channels, retention, deletion, incident response, and regulatory obligations. LicenseSizer documentation supports review but does not itself certify a dealership’s compliance.</p></section>
    <section><h2>Report a vulnerability</h2><p>Email <a href="mailto:security@licensesizer.com">security@licensesizer.com</a> with a clear description, reproduction steps, affected URL, and potential impact. Do not include real license images, customer information, credentials, or destructive test results. We ask researchers to avoid privacy violations, service disruption, and accessing data that is not their own.</p></section>
  </LegalShell>;
}
